"""add case number and content to judgment

Revision ID: 423ce3813481
Revises: 54acf0cdf6d9
Create Date: 2022-03-16 19:03:02.410389

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "423ce3813481"
down_revision = "54acf0cdf6d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("judgment", sa.Column("case_number", sa.String(), nullable=True))
    op.add_column("judgment", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("judgment", "content")
    op.drop_column("judgment", "case_number")
    # ### end Alembic commands ###
