"""Add source relation

Revision ID: 54acf0cdf6d9
Revises: 17cc2fc38779
Create Date: 2022-03-05 19:16:33.442723

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "54acf0cdf6d9"
down_revision = "17cc2fc38779"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "category",
            sa.Enum("Buy", "Hunt", "Sell", "Transport", name="sourcecategory"),
            nullable=False,
        ),
        sa.Column("occasion", sa.String(length=255), nullable=True),
        sa.Column("seller", sa.String(length=255), nullable=True),
        sa.Column("buyer", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=255), nullable=True),
        sa.Column("destination", sa.String(length=255), nullable=True),
        sa.Column("usage", sa.String(length=255), nullable=True),
        sa.Column("judgment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["judgment_id"],
            ["judgment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("judgment", sa.Column("location", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("judgment", "location")
    op.drop_table("source")
    # ### end Alembic commands ###
