"""add sentence field with datetime fields adjusted

Revision ID: 66f91403b875
Revises: 423ce3813481
Create Date: 2022-03-28 03:07:19.884514

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "66f91403b875"
down_revision = "423ce3813481"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("judgment", sa.Column("release_date", sa.Date(), nullable=True))
    op.add_column(
        "judgment",
        sa.Column(
            "creation_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column("judgment", sa.Column("sentence", sa.Text(), nullable=True))
    op.drop_column("judgment", "date_created")
    op.drop_column("judgment", "date_released")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judgment",
        sa.Column(
            "date_released", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "judgment",
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("judgment", "sentence")
    op.drop_column("judgment", "creation_time")
    op.drop_column("judgment", "release_date")
    # ### end Alembic commands ###
