"""add judgment table

Revision ID: b736b7d54146
Revises: a2a21f8f5f8e
Create Date: 2022-01-12 22:14:24.154539

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b736b7d54146"
down_revision = "a2a21f8f5f8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judgment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("date_released", sa.DateTime(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judgment_species",
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("judgment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["judgment_id"],
            ["judgment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["taxon_species.id"],
        ),
        sa.PrimaryKeyConstraint("species_id", "judgment_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("judgment_species")
    op.drop_table("judgment")
    # ### end Alembic commands ###
