"""make source related to defendant

Revision ID: b9315239e8c8
Revises: 66f91403b875
Create Date: 2022-03-30 01:34:59.193513

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9315239e8c8"
down_revision = "66f91403b875"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source", sa.Column("defendant_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "source", "defendant", ["defendant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "source", type_="foreignkey")
    op.drop_column("source", "defendant_id")
    # ### end Alembic commands ###
