"""make genus_id non-nullable

Revision ID: d12cd1dbac38
Revises: e793098ea682
Create Date: 2022-01-08 22:50:09.016576

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d12cd1dbac38"
down_revision = "e793098ea682"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxon_species", "genus_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxon_species", "genus_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
