"""create taxon tables

Revision ID: e793098ea682
Revises: 
Create Date: 2022-01-06 23:31:02.015367

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e793098ea682"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxon_class",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "taxon_order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["taxon_class.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "taxon_family",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["taxon_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "taxon_genus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["taxon_family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "taxon_species",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.Column("genus_id", sa.Integer(), nullable=True),
        sa.Column(
            "protection_class",
            sa.Enum("I", "II", name="protectionclass"),
            nullable=True,
        ),
        sa.Column(
            "conservation_status",
            sa.Enum(
                "EX",
                "EW",
                "CR",
                "EN",
                "VU",
                "NT",
                "CD",
                "LC",
                "DD",
                "NE",
                name="conservationstatus",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["genus_id"],
            ["taxon_genus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taxon_species")
    op.drop_table("taxon_genus")
    op.drop_table("taxon_family")
    op.drop_table("taxon_order")
    op.drop_table("taxon_class")
    # ### end Alembic commands ###
