"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys

import openapi_client
from openapi_client.model.defendant import Defendant


class TestDefendant(unittest.TestCase):
    """Defendant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefendant(self):
        """Test Defendant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Defendant()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
