"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.defendant import Defendant
from openapi_client.model.source import Source
from openapi_client.model.species_short import SpeciesShort
globals()['Defendant'] = Defendant
globals()['Source'] = Source
globals()['SpeciesShort'] = SpeciesShort
from openapi_client.model.judgment import Judgment


class TestJudgment(unittest.TestCase):
    """Judgment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJudgment(self):
        """Test Judgment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Judgment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
