"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conservation_status import ConservationStatus
from openapi_client.model.protection_class import ProtectionClass
globals()['ConservationStatus'] = ConservationStatus
globals()['ProtectionClass'] = ProtectionClass
from openapi_client.model.species import Species


class TestSpecies(unittest.TestCase):
    """Species unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecies(self):
        """Test Species"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Species()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
