#!/bin/sh

set -e

if [ "$#" -gt 0 ]; then
    poetry add $@
fi

echo "Exporting requirements"
mkdir -p requirements

set -x

poetry export -f requirements.txt -o requirements/min.txt --without-hashes
poetry export -f requirements.txt -o requirements/dev.txt --dev --without-hashes
